# Generated by Django 6.0.4 on 2026-04-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_secrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plugin_type', models.CharField(choices=[('blacklist', 'Sender Blacklist'), ('keyword', 'Keyword Filter'), ('regex', 'Regex Pattern'), ('domain_list', 'Trusted Domain List')], max_length=20)),
                ('rules', models.TextField(help_text='Newline-separated rules/entries')),
                ('author_id', models.CharField(max_length=255)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('installs', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plugins',
                'ordering': ['-installs', '-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_upvotes', to='core.plugin')),
            ],
            options={
                'db_table': 'plugin_upvotes',
                'unique_together': {('user_id', 'plugin')},
            },
        ),
        migrations.CreateModel(
            name='UserPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_installs', to='core.plugin')),
            ],
            options={
                'db_table': 'user_plugins',
                'unique_together': {('user_id', 'plugin')},
            },
        ),
    ]
